### ISSUE TITLE
Implement component to load evaluation data

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant-usecase-RAG#16]
The component should be able to load
- questions
- answers (optional)
- context (optional)

We might just want to extend the existing [`load_from_files`](https://github.com/ml6team/fondant/blob/main/components/load_from_files) component.

We should first define in which format we expect the data. I guess CSV would be the most straightforward, but I'm open to other optoins.

**Comment by mrchtr** [comment]
I guess we could leverage Fondant to generate an evaluation dataset.
Ragas offers as well a method for [synthetic test data generation](https://docs.ragas.io/en/latest/concepts/testset_generation.html#testset-generation). Maybe we implement something similar.

**Comment by Hakimovich99** [comment]
> I guess we could leverage Fondant to generate an evaluation dataset. Ragas offers as well a method for [synthetic test data generation](https://docs.ragas.io/en/latest/concepts/testset_generation.html#testset-generation). Maybe we implement something similar.

will take a look thanks!
